# Generated by Django 4.2.4 on 2023-08-28 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('new', 'new'), ('sale', 'sale')], max_length=7, null=True),
        ),
    ]
